blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/senseyman/mtproto/discussions
    about: Please ask and answer questions here.
  - name: Security issue
    url: https://github.com/senseyman/mtproto/blob/master/.github/SECURITY.md
    about: Report of any security vulnerabilities here.
